### ISSUE TITLE
Parser too slow

### ISSUE THREAD

**Issue by umangm** [ucla-pls/wiretap-tools#1]
It looks like the parser for converting wiretap binary files to plain text format is very slow.
It took more than 30 minutes to generate about 3 million events in one of the Dacapo benchmarks.

I would like to consider the possibility of writing my own parser, possibly in a different language like Java.
Is it hard and/or recommended ?
Can you send me instructions on how to read the history files in binary format ?

**Comment by kalhauge** [comment]
The parser is as I know not the bottleneck, but the printer. You can test this by 
running the 'count' command. Which should be *much* faster.

You can interface directly with the parser using haskell, or you can roll out your own parser which shouldn't be too difficult.

The format is described in https://github.com/ucla-pls/wiretap-tools/blob/master/src/Wiretap/Data/Event.hs. 

The format of each even is pretty much 
```
(thread : int32, order : int32, v : word8, [... variable length operation dependent on v])
```

Parseing each operation are described [here](https://github.com/ucla-pls/wiretap-tools/blob/master/src/Wiretap/Data/Event.hs#L252).

**Comment by kalhauge** [comment]
This part of the code might bee more illustrative: 

https://github.com/ucla-pls/wiretap-tools/blob/master/src/Wiretap/Data/Event.hs#L411

```haskell
getOperation :: Word8 -> Get Operation
getOperation w =
  case w .&. 0x0f of
    0 -> Synch . fromIntegral <$> getInt32be
    1 -> Fork <$> get
    2 -> Join <$> get
    3 -> Request <$> get
    4 -> Acquire <$> get
    5 -> Release <$> get
    6 -> return Begin
    7 -> return End
    8 -> return Branch
    10 -> Enter <$> get <*> get
    12 -> Read <$> getFieldLocation <*> getValue w
    13 -> Write <$> getFieldLocation <*> getValue w
    14 -> Read <$> getArrayLocation <*> getValue w
    15 -> Write <$> getArrayLocation <*> getValue w
    a -> error $ "Unknown event 0x" ++ showHex a ""
```

get is an overloaded operator that gets something of the type, and 
<$> means apply the function to the left to the results.

Fx:  `Fork <$> get` translates into Fork <$> get (Thread)

which has this definition:

```
newtype Thread = Thread
  { threadId :: Int32
  } deriving (Show, Eq, Ord)

instance Binary Thread where
  put = putInt32be . threadId
  get = Thread <$> getInt32be
```

So it acually says :: Fork <$> (Thread <$> getInt32be)

**Comment by umangm** [comment]
So, from what I understand, the file `wiretap.hist` is essentially a sequence of events, where each events is a fixed-length sequence of bytes. Is that correct ?

**Comment by kalhauge** [comment]
Each event has a variable size, begin has size (4 + 4 + 1) bytes , while Fork has size (4 + 4 + 1 + 4) bytes. Alternatively you can find the description of the format in the binary logger itself if you like to read Java more:

https://github.com/ucla-pls/wiretap/blob/master/src/main/java/edu/ucla/pls/wiretap/recorders/BinaryLogger.java

**Comment by umangm** [comment]
It is bit difficult to follow. Can you explain to me using an example trace?
Or better still, does a Skype chat work for you?

**Comment by kalhauge** [comment]
I did some improvements to the code in commit (f0e3fc2e06a821e259dcacef4ba16e465b72e89e) it should be available on develop. It now prints ~150k events per second. 

It should process the 3 million events in ~20 seconds. Does that fix your problem?

**Comment by umangm** [comment]
Wow this is amazing. This indeed fixes my problem. Thanks a ton!
You can close the issue for now.

**Comment by kalhauge** [comment]
Great!
