### ISSUE TITLE
Solver time

### ISSUE THREAD

**Issue by umangm** [ucla-pls/wiretap-tools#3]
Hi,

What are the units for the flag `--solver-time` (seconds, milliseconds, microseconds, something else)? Also , are there any recommended values for `--solver-time` and `--chunk-size` ?

**Comment by kalhauge** [comment]
The solver time is in milliseconds, it's given directly to Z3.

I would recommend a `--chunk-size` of 1000 - 10000 and `--chunk-offset` to half of chunk-size.
