### ISSUE TITLE
Stack space overflow. How to Use +RTS increase it.

### ISSUE THREAD

**Issue by lmnsyunhao** [ucla-pls/wiretap-tools#5]
Hello. When I running wiretap-tools on a trace contains 500,000 events. Here comes an error.
```
haoyun@tiger:~/getting-started/wiretap-tools$ wiretap-tools deadlocks /Data/share_pub/Dimmunix/trace/TestHashTable/wiretap.hist)
wiretap-tools: Stack space overflow: current size 33624 bytes.
wiretap-tools: Relink with -rtsopts and use `+RTS -Ksize -RTS' to increase it.
```
I have paid lots of effort trying to solve it.
```
haoyun@tiger:~/getting-started/wiretap-tools$ stack clean
haoyun@tiger:~/getting-started/wiretap-tools$ stack install --ghc-options -rtsopts
......
haoyun@tiger:~/getting-started/wiretap-tools$ stack exec +RTS -K80000M -RTS wiretap-tools deadlocks /Data/share_pub/Dimmunix/trace/TestHashTable/wiretap.hist
stack: Most RTS options are disabled. Link with -rtsopts to enable them.
haoyun@tiger:~/getting-started/wiretap-tools$ stack exec --ghc-options -rtsopts +RTS -K80000M -RTS wiretap-tools deadlocks /Data/share_pub/Dimmunix/trace/TestHashTable/wiretap.hist
stack: Most RTS options are disabled. Link with -rtsopts to enable them.
```
But, it doesn't work. How can I use +RTS to increasing the limit size of the stack? What is the correct command?
I appreciate your reply.

**Comment by kalhauge** [comment]
Thank you for the bug report.

1) Wiretap should not get a stack space overflow, I have tried to make it linear in space consumption, maybe set a smaller window size: `--chunk-size` and `--chunk-offset`, by not setting these it will try to load the entire history. This might also not scale well with the actual analysis. 

2) To fix the RTS problems you are having you just need to put the arguments the correct place:

    ```bash
    $ stack clean
    $ stack build --ghc-options -rtsopts
    $ stack exec -- wiretap-tools +RTS -K8000M -RTS ...
    #            ^^ this is important
    ```

Hope that helped!

**Comment by kalhauge** [comment]
I'll assume this fixed the problem :)
